# Generated by Django 3.2.15 on 2022-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(choices=[('tarjeta_de_identidad', 'Tarjeta de Identidad'), ('cedula', 'Cédula')], max_length=32)),
                ('identification', models.CharField(max_length=11, verbose_name='Número Identificación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número celular')),
            ],
        ),
    ]
